FROM node:16

RUN mkdir parse

ADD . /parse
WORKDIR /parse
RUN npm install

# VOLUMES =============================================
# Uncomment if you want to access cloud code, logs & configs outside of your container

# VOLUME /extensions
# VOLUME /logs
# VOLUME /configs

# RUN =================================================

EXPOSE 1337
CMD [ "npm", "start" ]